title Jing Guo 
author Jing Guo
description Polytechnique Montréal
permalink title
lang en
excerpt_separator nnn
date_format %B %d, %Y

# Layout

show_excerpts false             # show article excerpts instead of archive list on the home page
show_frame true                # display a grey frame on large screens
show_sidebar false             # show a sidebar instead of the usual header
minimal false                 # remove all clutter

# Menu                          # for available icons see httpsfontawesome.comv5icons

navigation                     # accepts {file, title, url, icon, sidebaricon}
  - {title Home, file index.md}
  - {title Research, file research.md}
  - {title Group, file group.md}
  - {title Teaching, file teaching.md}

external                       # accepts {file, title, url, icon, sidebaricon}
  - {title Mail, icon envelope, url mailtojing.guo@polymtl.ca}
  - {title Github, icon github, url httpsgithub.comjingguo89}
  - {title GoogleScholar, icon google-scholar, url httpsscholar.google.comcitationsuser=bWUA1EgAAAAJ&hl=en}

comments
#  disqus_shortname          # see httpsdisqus.com
#  isso_domain               # see httpsisso-comments.de

plugins
 - jekyll-feed
